package graph

import (
	"database/sql"
	"net/http"

	"github.com/go-redis/redis/v8"
)

// This file will not be regenerated by gqlgen.
//
// This is where you declare dependencies you want to inject into your 
// resolvers, such as database connections or internal service clients.

type Resolver struct {
	// DB is our primary PostgreSQL connection for user data
	DB *sql.DB

	// RDB is the Redis client for sale price caching (Memorystore)
	RDB *redis.Client

	// HttpClient for calling the Python Plan Engine (FastAPI)
	PlanEngineClient *http.Client
}