// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Item struct {
	ID           string   `json:"id"`
	Sku          *string  `json:"sku,omitempty"`
	Name         string   `json:"name"`
	Brand        *string  `json:"brand,omitempty"`
	PriceCurrent *float64 `json:"priceCurrent,omitempty"`
	PriceRegular *float64 `json:"priceRegular,omitempty"`
	PriceLabel   *string  `json:"priceLabel,omitempty"`
	Category     *string  `json:"category,omitempty"`
	ImageURL     *string  `json:"imageUrl,omitempty"`
}

type LoginUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	ZipCode  string `json:"zipCode"`
}

type Plan struct {
	ID             string `json:"id"`
	Age            int    `json:"age"`
	Gender         string `json:"gender"`
	ActivityLevel  string `json:"activityLevel"`
	WeeklyCalories int    `json:"weeklyCalories"`
	DailyProtein   int    `json:"dailyProtein"`
}

type Recipe struct {
	ID            string   `json:"id"`
	Title         string   `json:"title"`
	Instructions  string   `json:"instructions"`
	EstimatedCost *float64 `json:"estimatedCost,omitempty"`
	Items         []*Item  `json:"items,omitempty"`
	ImageURL      *string  `json:"imageUrl,omitempty"`
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}
